### ISSUE TITLE
misleading error message when GitHub access token is missing/wrong/expired

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/credential-status-manager-git#16]
I get this error when starting up the status manager, if my GitHub access token is missing, incorrect, or expired:

Error: The credential status repo ("status-test-three") and the credential status metadata repo ("status-test-meta-three") must be manually created in advance.
    at createStatusManager (file:///Users/jameschartrand/Documents/github/dcc/status-service/node_modules/@digitalcredentials/credential-status-manager-git/dist/esm/credential-status-manager-index.js:61:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async initializeStatusManager (file:///Users/jameschartrand/Documents/github/dcc/status-service/src/status.js:16:31)
    at async build (file:///Users/jameschartrand/Documents/github/dcc/status-service/src/app.js:10:5)
    at async run (file:///Users/jameschartrand/Documents/github/dcc/status-service/server.js:11:15)

The repositories do exist, it is just the GitHub access token that is incorrect.

Could at some point maybe return a more specific error.

**Comment by kayaelle** [comment]
@alexfigtree @jchartrand - still an issue? Spitshine?

**Comment by jchartrand** [comment]
@kayaelle As with https://github.com/digitalcredentials/credential-status-manager-git/issues/26#issuecomment-3192832634 this repo should be retired. I've added a deprecate label.

**Comment by alexfigtree** [comment]
Will close based on James' comment
